### PR TITLE
fixed getting volcano info from online source

### PR DESCRIPTION
**Pull request by ubdbra001**
Hi @jgliss,

I'm working on a project that has pyplis as a dependency, and noticed that the getting volcano info from the NOAA was broken by the site change.
So, I've updated the get_source_info_online function to use the NOAA API and added a function to ensure the dictionary returned matches the pyplis naming conventions.

I'v tried to keep the output as close to the original as possible to prevent any breakages, but it would be good if you could take a look.

Dan

### CODE REVIEW

**Comment by jgliss** [comment]
Fixes #35

**Comment by ubdbra001** [comment]
No problem! Sure, will do this week

**Comment by ubdbra001** [comment]
Hi @jgliss,

Just added and pushed a test for the fix. It covers the main use case, but let me know if you'd like more.

Dan

**Comment by jgliss** [comment]
Thanks, @ubdbra001 I will check!

**Comment by jgliss** [comment]
@ubdbra001 it seems like I need to update the CI workflow first (remove unsupported python versions etc) and you will probably need to update your branch against v145dev once I have fixed the workflow. I will ping you once this is done!

**Comment by jgliss** [comment]
@ubdbra001 I updated the workflow and environments (see #45) in v145dev, could you please update your branch so I can trigger the pipeline once more? Cheers

**Comment by ubdbra001** [comment]
@jgliss Done, awaiting workflow approval now

**Review by jgliss — APPROVED** [review]
This looks great, many thanks @ubdbra001 for fixing this issue.

**Pull request merged**
