### PR TITLE
Py3 cleanup

### PR DESCRIPTION
**Pull request by johannjacobsohn**
Some lint cleanup and wording commits, an odd pytest fix (fed120a) caused by a bug in astropy, improve error handling in tests scripts (c88c817) which would otherwise run happily and report no problems even if tests failed, as well as a fixed requirements file for tox (c28dd7c).

Also replaced from_csv with read_csv (fc70375) as the first has been deprecated and removed:
- https://pandas.pydata.org/pandas-docs/stable/whatsnew/v0.25.0.html?highlight=from_csv#removal-of-prior-version-deprecations-changes
- https://github.com/pandas-dev/pandas/issues/4191

### CODE REVIEW

**Comment by jgliss** [comment]
@johannjacobsohn thanks for this PR and for further testing. Can you maybe specify a bit more detailed your system setup and what tests were failing in `ex06_doas_calib.py` before you increased the tolerance level of the tests (which test variables, and which values did you get)? I am asking because, as you know, the calibration is crucial for the emission-rate retrieval and I think we should aim for getting the same results, no matter which platform or python version, etc., within a tolerance level, that we consider sufficient. I am afraid, we'll forget about it, if I merge this now ;)

**Comment by johannjacobsohn** [comment]
@jgliss that is true, I switched to conda and reverted b523bbf, which has disappeared by itself (?). Also replaced from_csv w/ read read_csv becaused it crashed with newer versions of pandas/py3

**Comment by jgliss** [comment]
Thanks @johannjacobsohn. `pandas.read_csv` is backwards compatible with older pandas versions, right?

**Comment by johannjacobsohn** [comment]
> Thanks @johannjacobsohn. `pandas.read_csv` is backwards compatible with older pandas versions, right?

yes

**Pull request merged**
